# Generated by Django 3.0.2 on 2020-01-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(default='https:/test.com/goblok.png', max_length=255),
        ),
    ]
