# Generated by Django 3.0.2 on 2020-01-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='article.Author'),
        ),
    ]
