# Generated by Django 3.0.2 on 2020-01-12 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200111_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.Article')),
            ],
        ),
    ]
